#!usr/bin/env python
__author__    = "Westwood Robotics Corporation"
__email__     = "info@westwoodrobotics.io"
__copyright__ = "Copyright 2025 Westwood Robotics Corporation"
__date__      = "November 3, 2023"
__update__    = "August 25, 2025"
__project__   = "AOS"
__version__   = "0.1.0"
__status__    = "Production"

'''
Script that holds useful BEAR macros
'''

from collections import defaultdict
from Setting.Macros.constant_macros import *


# ==================================================
# ==================================================
# BEAR INFO
# ==================================================
# ==================================================
BEAR = defaultdict(lambda: defaultdict(int))

# ------------------------------
# BEAR PROPERTY
# ------------------------------
BEAR_ID                = 0
BEAR_POSITION_LIMIT    = 1
BEAR_CURRENT_LIMIT     = 2
BEAR_TEMPERATURE_LIMIT = 3
BEAR_GEAR_RATIO        = 4
BEAR_TORQUE_CONSTANT   = 5
BEAR_REFLECTED_INERTIA = 6
BEAR_POSITION_PID      = 7
BEAR_VELOCITY_PID      = 8
BEAR_FORCE_PID         = 9
BEAR_IQ_PID            = 10
BEAR_ID_PID            = 11

BEAR_HIP_YAW_R        = 1
BEAR_HIP_ROLL_R       = 2
BEAR_HIP_PITCH_R      = 3
BEAR_KNEE_R           = 4
BEAR_ANKLE_IN_R       = 5
BEAR_ANKLE_OUT_R      = 6

BEAR_HIP_YAW_L        = 7
BEAR_HIP_ROLL_L       = 8
BEAR_HIP_PITCH_L      = 9
BEAR_KNEE_L           = 10
BEAR_ANKLE_IN_L       = 11
BEAR_ANKLE_OUT_L      = 12

BEAR_SHOULDER_PITCH_R = 13
BEAR_SHOULDER_ROLL_R  = 14
BEAR_SHOULDER_YAW_R   = 15
BEAR_ELBOW_PITCH_R    = 16
BEAR_ELBOW_YAW_R      = 17
BEAR_WRIST_PITCH_R    = 18
BEAR_WRIST_YAW_R      = 19

BEAR_SHOULDER_PITCH_L = 20
BEAR_SHOULDER_ROLL_L  = 21
BEAR_SHOULDER_YAW_L   = 22
BEAR_ELBOW_PITCH_L    = 23
BEAR_ELBOW_YAW_L      = 24
BEAR_WRIST_PITCH_L    = 25
BEAR_WRIST_YAW_L      = 26

BEAR_HEAD_YAW         = 27
BEAR_HEAD_PITCH       = 28

# ------------------------------
# BEAR ID
# ------------------------------
LEG_R_BEAR_ID_LIST = [BEAR_HIP_YAW_R, BEAR_HIP_ROLL_R, BEAR_HIP_PITCH_R, BEAR_KNEE_R, BEAR_ANKLE_IN_R, BEAR_ANKLE_OUT_R]
LEG_L_BEAR_ID_LIST = [BEAR_HIP_YAW_L, BEAR_HIP_ROLL_L, BEAR_HIP_PITCH_L, BEAR_KNEE_L, BEAR_ANKLE_IN_L, BEAR_ANKLE_OUT_L]
ARM_R_BEAR_ID_LIST = [BEAR_SHOULDER_PITCH_R, BEAR_SHOULDER_ROLL_R, BEAR_SHOULDER_YAW_R, BEAR_ELBOW_PITCH_R, BEAR_ELBOW_YAW_R, BEAR_WRIST_PITCH_R, BEAR_WRIST_YAW_R]
ARM_L_BEAR_ID_LIST = [BEAR_SHOULDER_PITCH_L, BEAR_SHOULDER_ROLL_L, BEAR_SHOULDER_YAW_L, BEAR_ELBOW_PITCH_L, BEAR_ELBOW_YAW_L, BEAR_WRIST_PITCH_L, BEAR_WRIST_YAW_L]
HEAD_BEAR_ID_LIST  = [BEAR_HEAD_YAW, BEAR_HEAD_PITCH]

LEG_BEAR_ID_LIST        = LEG_R_BEAR_ID_LIST + LEG_L_BEAR_ID_LIST
ARM_BEAR_ID_LIST        = ARM_R_BEAR_ID_LIST + ARM_L_BEAR_ID_LIST
UPPER_BODY_BEAR_ID_LIST =   ARM_BEAR_ID_LIST +  HEAD_BEAR_ID_LIST
ROBOT_BEAR_ID_LIST      =   LEG_BEAR_ID_LIST + UPPER_BODY_BEAR_ID_LIST

for bear in ROBOT_BEAR_ID_LIST:
    BEAR[BEAR_ID][bear] = bear

# ------------------------------
# BEAR POSITION LIMIT
# ------------------------------
BEAR[BEAR_POSITION_LIMIT][BEAR_HIP_YAW_R]   = [-1.4, 1.4]
BEAR[BEAR_POSITION_LIMIT][BEAR_HIP_ROLL_R]  = [-1.4, 1.4]
BEAR[BEAR_POSITION_LIMIT][BEAR_HIP_PITCH_R] = [-2.0, 2.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_KNEE_R]      = [-0.5, 2.4]
BEAR[BEAR_POSITION_LIMIT][BEAR_ANKLE_IN_R]  = [-1.5, 1.5]
BEAR[BEAR_POSITION_LIMIT][BEAR_ANKLE_OUT_R] = [-1.5, 1.5]

BEAR[BEAR_POSITION_LIMIT][BEAR_HIP_YAW_L]   = [-1.4, 1.4]
BEAR[BEAR_POSITION_LIMIT][BEAR_HIP_ROLL_L]  = [-1.4, 1.4]
BEAR[BEAR_POSITION_LIMIT][BEAR_HIP_PITCH_L] = [-2.0, 2.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_KNEE_L]      = [-2.4, 0.5]
BEAR[BEAR_POSITION_LIMIT][BEAR_ANKLE_IN_L]  = [-1.5, 1.5]
BEAR[BEAR_POSITION_LIMIT][BEAR_ANKLE_OUT_L] = [-1.5, 1.5]

BEAR[BEAR_POSITION_LIMIT][BEAR_SHOULDER_PITCH_R] = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_SHOULDER_ROLL_R]  = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_SHOULDER_YAW_R]   = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_ELBOW_PITCH_R]    = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_ELBOW_YAW_R]      = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_WRIST_PITCH_R]    = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_WRIST_YAW_R]      = [-3.0, +3.0]

BEAR[BEAR_POSITION_LIMIT][BEAR_SHOULDER_PITCH_L] = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_SHOULDER_ROLL_L]  = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_SHOULDER_YAW_L]   = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_ELBOW_PITCH_L]    = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_ELBOW_YAW_L]      = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_WRIST_PITCH_L]    = [-3.0, +3.0]
BEAR[BEAR_POSITION_LIMIT][BEAR_WRIST_YAW_L]      = [-3.0, +3.0]

BEAR[BEAR_POSITION_LIMIT][BEAR_HEAD_YAW]   = [-PI_2, PI_2]
BEAR[BEAR_POSITION_LIMIT][BEAR_HEAD_PITCH] = [-PI_2, PI_2]

# ------------------------------
# BEAR CURRENT LIMIT
# ------------------------------
BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_YAW_R]   = [-50, +50]
BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_ROLL_R]  = [-50, +50]
BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_PITCH_R] = [-50, +50]
BEAR[BEAR_CURRENT_LIMIT][BEAR_KNEE_R]      = [-60, +60]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ANKLE_IN_R]  = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ANKLE_OUT_R] = [-20, +20]

BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_YAW_L]   = BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_YAW_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_ROLL_L]  = BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_ROLL_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_PITCH_L] = BEAR[BEAR_CURRENT_LIMIT][BEAR_HIP_PITCH_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_KNEE_L]      = BEAR[BEAR_CURRENT_LIMIT][BEAR_KNEE_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ANKLE_IN_L]  = BEAR[BEAR_CURRENT_LIMIT][BEAR_ANKLE_IN_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ANKLE_OUT_L] = BEAR[BEAR_CURRENT_LIMIT][BEAR_ANKLE_OUT_R]

BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_PITCH_R] = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_ROLL_R]  = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_YAW_R]   = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ELBOW_PITCH_R]    = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ELBOW_YAW_R]      = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_WRIST_PITCH_R]    = [-20, +20]
BEAR[BEAR_CURRENT_LIMIT][BEAR_WRIST_YAW_R]      = [-20, +20]

BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_CURRENT_LIMIT][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_CURRENT_LIMIT][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_CURRENT_LIMIT][BEAR_ELBOW_YAW_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_CURRENT_LIMIT][BEAR_WRIST_PITCH_R]
BEAR[BEAR_CURRENT_LIMIT][BEAR_WRIST_YAW_L]      = BEAR[BEAR_CURRENT_LIMIT][BEAR_WRIST_YAW_R]

BEAR[BEAR_CURRENT_LIMIT][BEAR_HEAD_YAW]   = [-10, +10]
BEAR[BEAR_CURRENT_LIMIT][BEAR_HEAD_PITCH] = [-10, +10]

# ------------------------------
# BEAR TEMPERATURE LIMIT
# ------------------------------
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_YAW_R]   = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_ROLL_R]  = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_PITCH_R] = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_KNEE_R]      = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ANKLE_IN_R]  = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ANKLE_OUT_R] = [90, 110]

BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_YAW_L]   = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_YAW_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_ROLL_L]  = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_ROLL_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_PITCH_L] = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HIP_PITCH_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_KNEE_L]      = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_KNEE_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ANKLE_IN_L]  = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ANKLE_IN_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ANKLE_OUT_L] = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ANKLE_OUT_R]

BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_PITCH_R] = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_ROLL_R]  = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_YAW_R]   = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ELBOW_PITCH_R]    = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ELBOW_YAW_R]      = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_WRIST_PITCH_R]    = [90, 110]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_WRIST_YAW_R]      = [90, 110]

BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_ELBOW_YAW_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_WRIST_PITCH_R]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_WRIST_YAW_L]      = BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_WRIST_YAW_R]

BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HEAD_YAW]   = [80, 100]
BEAR[BEAR_TEMPERATURE_LIMIT][BEAR_HEAD_PITCH] = [80, 100]

# ------------------------------
# BEAR GEAR RATIO
# ------------------------------
BEAR[BEAR_GEAR_RATIO][BEAR_HIP_YAW_R]   = 9.00
BEAR[BEAR_GEAR_RATIO][BEAR_HIP_ROLL_R]  = 9.00
BEAR[BEAR_GEAR_RATIO][BEAR_HIP_PITCH_R] = 7.78
BEAR[BEAR_GEAR_RATIO][BEAR_KNEE_R]      = 7.78
BEAR[BEAR_GEAR_RATIO][BEAR_ANKLE_IN_R]  = 20.0
BEAR[BEAR_GEAR_RATIO][BEAR_ANKLE_OUT_R] = 20.0

BEAR[BEAR_GEAR_RATIO][BEAR_HIP_YAW_L]   = BEAR[BEAR_GEAR_RATIO][BEAR_HIP_YAW_R]
BEAR[BEAR_GEAR_RATIO][BEAR_HIP_ROLL_L]  = BEAR[BEAR_GEAR_RATIO][BEAR_HIP_ROLL_R]
BEAR[BEAR_GEAR_RATIO][BEAR_HIP_PITCH_L] = BEAR[BEAR_GEAR_RATIO][BEAR_HIP_PITCH_R]
BEAR[BEAR_GEAR_RATIO][BEAR_KNEE_L]      = BEAR[BEAR_GEAR_RATIO][BEAR_KNEE_R]
BEAR[BEAR_GEAR_RATIO][BEAR_ANKLE_IN_L]  = BEAR[BEAR_GEAR_RATIO][BEAR_ANKLE_IN_R]
BEAR[BEAR_GEAR_RATIO][BEAR_ANKLE_OUT_L] = BEAR[BEAR_GEAR_RATIO][BEAR_ANKLE_OUT_R]

BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_PITCH_R] = 9.00
BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_ROLL_R]  = 20.0
BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_YAW_R]   = 20.0
BEAR[BEAR_GEAR_RATIO][BEAR_ELBOW_PITCH_R]    = 20.0
BEAR[BEAR_GEAR_RATIO][BEAR_ELBOW_YAW_R]      = 20.0
BEAR[BEAR_GEAR_RATIO][BEAR_WRIST_PITCH_R]    = 20.0
BEAR[BEAR_GEAR_RATIO][BEAR_WRIST_YAW_R]      = 20.0

BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_GEAR_RATIO][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_GEAR_RATIO][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_GEAR_RATIO][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_GEAR_RATIO][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_GEAR_RATIO][BEAR_ELBOW_YAW_R]
BEAR[BEAR_GEAR_RATIO][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_GEAR_RATIO][BEAR_WRIST_PITCH_R]
BEAR[BEAR_GEAR_RATIO][BEAR_WRIST_YAW_L]      = BEAR[BEAR_GEAR_RATIO][BEAR_WRIST_YAW_R]

BEAR[BEAR_GEAR_RATIO][BEAR_HEAD_YAW]   = 9.00
BEAR[BEAR_GEAR_RATIO][BEAR_HEAD_PITCH] = 9.00

# ------------------------------
# BEAR TORQUE CONSTANT
# ------------------------------
BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_YAW_R]   = 2.62
BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_ROLL_R]  = 2.62
BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_PITCH_R] = 2.86
BEAR[BEAR_TORQUE_CONSTANT][BEAR_KNEE_R]      = 2.86
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ANKLE_IN_R]  = 1.34
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ANKLE_OUT_R] = 1.34

BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_YAW_L]   = BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_YAW_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_ROLL_L]  = BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_ROLL_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_PITCH_L] = BEAR[BEAR_TORQUE_CONSTANT][BEAR_HIP_PITCH_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_KNEE_L]      = BEAR[BEAR_TORQUE_CONSTANT][BEAR_KNEE_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ANKLE_IN_L]  = BEAR[BEAR_TORQUE_CONSTANT][BEAR_ANKLE_IN_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ANKLE_OUT_L] = BEAR[BEAR_TORQUE_CONSTANT][BEAR_ANKLE_OUT_R]

BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_PITCH_R] = 1.12
BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_ROLL_R]  = 1.34
BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_YAW_R]   = 1.34
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ELBOW_PITCH_R]    = 1.34
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ELBOW_YAW_R]      = 1.34
BEAR[BEAR_TORQUE_CONSTANT][BEAR_WRIST_PITCH_R]    = 1.34
BEAR[BEAR_TORQUE_CONSTANT][BEAR_WRIST_YAW_R]      = 1.34

BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_TORQUE_CONSTANT][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_TORQUE_CONSTANT][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_TORQUE_CONSTANT][BEAR_ELBOW_YAW_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_TORQUE_CONSTANT][BEAR_WRIST_PITCH_R]
BEAR[BEAR_TORQUE_CONSTANT][BEAR_WRIST_YAW_L]      = BEAR[BEAR_TORQUE_CONSTANT][BEAR_WRIST_YAW_R]


BEAR[BEAR_TORQUE_CONSTANT][BEAR_HEAD_YAW]   = 0.35
BEAR[BEAR_TORQUE_CONSTANT][BEAR_HEAD_PITCH] = 0.35

# ------------------------------
# BEAR REFLECTED INERTIA
# ------------------------------
BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_YAW_R]   = 0.0741
BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_ROLL_R]  = 0.0741
BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_PITCH_R] = 0.1153
BEAR[BEAR_REFLECTED_INERTIA][BEAR_KNEE_R]      = 0.1153
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ANKLE_IN_R]  = 0.0090
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ANKLE_OUT_R] = 0.0090

BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_YAW_L]   = BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_YAW_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_ROLL_L]  = BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_ROLL_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_PITCH_L] = BEAR[BEAR_REFLECTED_INERTIA][BEAR_HIP_PITCH_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_KNEE_L]      = BEAR[BEAR_REFLECTED_INERTIA][BEAR_KNEE_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ANKLE_IN_L]  = BEAR[BEAR_REFLECTED_INERTIA][BEAR_ANKLE_IN_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ANKLE_OUT_L] = BEAR[BEAR_REFLECTED_INERTIA][BEAR_ANKLE_OUT_R]

BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_PITCH_R] = 0.0136
BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_ROLL_R]  = 0.0090
BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_YAW_R]   = 0.0090
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ELBOW_PITCH_R]    = 0.0090
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ELBOW_YAW_R]      = 0.0090
BEAR[BEAR_REFLECTED_INERTIA][BEAR_WRIST_PITCH_R]    = 0.0090
BEAR[BEAR_REFLECTED_INERTIA][BEAR_WRIST_YAW_R]      = 0.0090

BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_REFLECTED_INERTIA][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_REFLECTED_INERTIA][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_REFLECTED_INERTIA][BEAR_ELBOW_YAW_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_REFLECTED_INERTIA][BEAR_WRIST_PITCH_R]
BEAR[BEAR_REFLECTED_INERTIA][BEAR_WRIST_YAW_L]      = BEAR[BEAR_REFLECTED_INERTIA][BEAR_WRIST_YAW_R]

BEAR[BEAR_REFLECTED_INERTIA][BEAR_HEAD_YAW]   = 0.00182
BEAR[BEAR_REFLECTED_INERTIA][BEAR_HEAD_PITCH] = 0.00182

# ------------------------------
# BEAR POSITION PID GAINS
# ------------------------------
BEAR[BEAR_POSITION_PID][BEAR_HIP_YAW_R]   = [300, 0, 2.5]
BEAR[BEAR_POSITION_PID][BEAR_HIP_ROLL_R]  = [300, 0, 2.5]
BEAR[BEAR_POSITION_PID][BEAR_HIP_PITCH_R] = [400, 0, 2.5]
BEAR[BEAR_POSITION_PID][BEAR_KNEE_R]      = [400, 0, 2.5]
BEAR[BEAR_POSITION_PID][BEAR_ANKLE_IN_R]  = [300, 0, 2.5]
BEAR[BEAR_POSITION_PID][BEAR_ANKLE_OUT_R] = [300, 0, 2.5]

BEAR[BEAR_POSITION_PID][BEAR_HIP_YAW_L]   = BEAR[BEAR_POSITION_PID][BEAR_HIP_YAW_R]
BEAR[BEAR_POSITION_PID][BEAR_HIP_ROLL_L]  = BEAR[BEAR_POSITION_PID][BEAR_HIP_ROLL_R]
BEAR[BEAR_POSITION_PID][BEAR_HIP_PITCH_L] = BEAR[BEAR_POSITION_PID][BEAR_HIP_PITCH_R]
BEAR[BEAR_POSITION_PID][BEAR_KNEE_L]      = BEAR[BEAR_POSITION_PID][BEAR_KNEE_R]
BEAR[BEAR_POSITION_PID][BEAR_ANKLE_IN_L]  = BEAR[BEAR_POSITION_PID][BEAR_ANKLE_IN_R]
BEAR[BEAR_POSITION_PID][BEAR_ANKLE_OUT_L] = BEAR[BEAR_POSITION_PID][BEAR_ANKLE_OUT_R]

BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_PITCH_R] = [200, 0, 2]
BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_ROLL_R]  = [200, 0, 2]
BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_YAW_R]   = [200, 0, 2]
BEAR[BEAR_POSITION_PID][BEAR_ELBOW_PITCH_R]    = [200, 0, 2]
BEAR[BEAR_POSITION_PID][BEAR_ELBOW_YAW_R]      = [200, 0, 2]
BEAR[BEAR_POSITION_PID][BEAR_WRIST_PITCH_R]    = [200, 0, 2]
BEAR[BEAR_POSITION_PID][BEAR_WRIST_YAW_R]      = [200, 0, 2]

BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_POSITION_PID][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_POSITION_PID][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_POSITION_PID][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_POSITION_PID][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_POSITION_PID][BEAR_ELBOW_YAW_R]
BEAR[BEAR_POSITION_PID][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_POSITION_PID][BEAR_WRIST_PITCH_R]
BEAR[BEAR_POSITION_PID][BEAR_WRIST_YAW_L]      = BEAR[BEAR_POSITION_PID][BEAR_WRIST_YAW_R]  

BEAR[BEAR_POSITION_PID][BEAR_HEAD_YAW]   = [30, 0, 1]
BEAR[BEAR_POSITION_PID][BEAR_HEAD_PITCH] = [30, 0, 1]

# ------------------------------
# BEAR VELOCITY PID GAINS
# ------------------------------
BEAR[BEAR_VELOCITY_PID][BEAR_HIP_YAW_R]   = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_HIP_ROLL_R]  = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_HIP_PITCH_R] = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_KNEE_R]      = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_ANKLE_IN_R]  = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_ANKLE_OUT_R] = [1, 0, 0]

BEAR[BEAR_VELOCITY_PID][BEAR_HIP_YAW_L]   = BEAR[BEAR_VELOCITY_PID][BEAR_HIP_YAW_R]
BEAR[BEAR_VELOCITY_PID][BEAR_HIP_ROLL_L]  = BEAR[BEAR_VELOCITY_PID][BEAR_HIP_ROLL_R]
BEAR[BEAR_VELOCITY_PID][BEAR_HIP_PITCH_L] = BEAR[BEAR_VELOCITY_PID][BEAR_HIP_PITCH_R]
BEAR[BEAR_VELOCITY_PID][BEAR_KNEE_L]      = BEAR[BEAR_VELOCITY_PID][BEAR_KNEE_R]
BEAR[BEAR_VELOCITY_PID][BEAR_ANKLE_IN_L]  = BEAR[BEAR_VELOCITY_PID][BEAR_ANKLE_IN_R]
BEAR[BEAR_VELOCITY_PID][BEAR_ANKLE_OUT_L] = BEAR[BEAR_VELOCITY_PID][BEAR_ANKLE_OUT_R]

BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_PITCH_R] = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_ROLL_R]  = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_YAW_R]   = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_ELBOW_PITCH_R]    = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_ELBOW_YAW_R]      = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_WRIST_PITCH_R]    = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_WRIST_YAW_R]      = [1, 0, 0]

BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_VELOCITY_PID][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_VELOCITY_PID][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_VELOCITY_PID][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_VELOCITY_PID][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_VELOCITY_PID][BEAR_ELBOW_YAW_R]
BEAR[BEAR_VELOCITY_PID][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_VELOCITY_PID][BEAR_WRIST_PITCH_R]
BEAR[BEAR_VELOCITY_PID][BEAR_WRIST_YAW_L]      = BEAR[BEAR_VELOCITY_PID][BEAR_WRIST_YAW_R]

BEAR[BEAR_VELOCITY_PID][BEAR_HEAD_YAW]   = [1, 0, 0]
BEAR[BEAR_VELOCITY_PID][BEAR_HEAD_PITCH] = [1, 0, 0]

# ------------------------------
# BEAR FORCE PID GAINS
# ------------------------------
for bear in ROBOT_BEAR_ID_LIST:
    BEAR[BEAR_FORCE_PID][bear] = BEAR[BEAR_POSITION_PID][bear]

# ------------------------------
# BEAR IQ PID GAINS
# ------------------------------
BEAR[BEAR_IQ_PID][BEAR_HIP_YAW_R]   = [0.184, 0.065, 0]
BEAR[BEAR_IQ_PID][BEAR_HIP_ROLL_R]  = [0.184, 0.065, 0]
BEAR[BEAR_IQ_PID][BEAR_HIP_PITCH_R] = [0.250, 0.017, 0]
BEAR[BEAR_IQ_PID][BEAR_KNEE_R]      = [0.250, 0.017, 0]
BEAR[BEAR_IQ_PID][BEAR_ANKLE_IN_R]  = [0.358, 0.045, 0]
BEAR[BEAR_IQ_PID][BEAR_ANKLE_OUT_R] = [0.358, 0.045, 0]

BEAR[BEAR_IQ_PID][BEAR_HIP_YAW_L]   = BEAR[BEAR_IQ_PID][BEAR_HIP_YAW_R]
BEAR[BEAR_IQ_PID][BEAR_HIP_ROLL_L]  = BEAR[BEAR_IQ_PID][BEAR_HIP_ROLL_R]
BEAR[BEAR_IQ_PID][BEAR_HIP_PITCH_L] = BEAR[BEAR_IQ_PID][BEAR_HIP_PITCH_R]
BEAR[BEAR_IQ_PID][BEAR_KNEE_L]      = BEAR[BEAR_IQ_PID][BEAR_KNEE_R]
BEAR[BEAR_IQ_PID][BEAR_ANKLE_IN_L]  = BEAR[BEAR_IQ_PID][BEAR_ANKLE_IN_R]
BEAR[BEAR_IQ_PID][BEAR_ANKLE_OUT_L] = BEAR[BEAR_IQ_PID][BEAR_ANKLE_OUT_R]

BEAR[BEAR_IQ_PID][BEAR_SHOULDER_PITCH_R] = [0.184, 0.065, 0]
BEAR[BEAR_IQ_PID][BEAR_SHOULDER_ROLL_R]  = [0.358, 0.045, 0]
BEAR[BEAR_IQ_PID][BEAR_SHOULDER_YAW_R]   = [0.358, 0.045, 0]
BEAR[BEAR_IQ_PID][BEAR_ELBOW_PITCH_R]    = [0.358, 0.045, 0]
BEAR[BEAR_IQ_PID][BEAR_ELBOW_YAW_R]      = [0.358, 0.045, 0]
BEAR[BEAR_IQ_PID][BEAR_WRIST_PITCH_R]    = [0.358, 0.045, 0]
BEAR[BEAR_IQ_PID][BEAR_WRIST_YAW_R]      = [0.358, 0.045, 0]

BEAR[BEAR_IQ_PID][BEAR_SHOULDER_PITCH_L] = BEAR[BEAR_IQ_PID][BEAR_SHOULDER_PITCH_R]
BEAR[BEAR_IQ_PID][BEAR_SHOULDER_ROLL_L]  = BEAR[BEAR_IQ_PID][BEAR_SHOULDER_ROLL_R]
BEAR[BEAR_IQ_PID][BEAR_SHOULDER_YAW_L]   = BEAR[BEAR_IQ_PID][BEAR_SHOULDER_YAW_R]
BEAR[BEAR_IQ_PID][BEAR_ELBOW_PITCH_L]    = BEAR[BEAR_IQ_PID][BEAR_ELBOW_PITCH_R]
BEAR[BEAR_IQ_PID][BEAR_ELBOW_YAW_L]      = BEAR[BEAR_IQ_PID][BEAR_ELBOW_YAW_R]
BEAR[BEAR_IQ_PID][BEAR_WRIST_PITCH_L]    = BEAR[BEAR_IQ_PID][BEAR_WRIST_PITCH_R]
BEAR[BEAR_IQ_PID][BEAR_WRIST_YAW_L]      = BEAR[BEAR_IQ_PID][BEAR_WRIST_YAW_R]

BEAR[BEAR_IQ_PID][BEAR_HEAD_YAW]   = [0.277, 0.061, 0]
BEAR[BEAR_IQ_PID][BEAR_HEAD_PITCH] = [0.277, 0.061, 0]

# ------------------------------
# BEAR ID PID GAINS
# ------------------------------
for bear in ROBOT_BEAR_ID_LIST:
    BEAR[BEAR_ID_PID][bear] = BEAR[BEAR_IQ_PID][bear]
