#!usr/bin/env python
__author__    = "Westwood Robotics Corporation"
__email__     = "info@westwoodrobotics.io"
__copyright__ = "Copyright 2025 Westwood Robotics Corporation"
__date__      = "February 21, 2025"
__update__    = "August 25, 2025"
__project__   = "AOS"
__version__   = "0.1.0"
__status__    = "Production"

'''
Script that holds useful DXL (XL330-M288-T) macros
'''

from collections import defaultdict
from Setting.Macros.constant_macros import *


# ==================================================
# ==================================================
# DXL INFO
# ==================================================
# ==================================================
DXL = defaultdict(lambda: defaultdict(int))


# ------------------------------
# DXL REGISTER ADDRESS AND SIZE (https://emanual.robotis.com/docs/en/dxl/x/xl330-m288)
# ------------------------------
DXL_REGISTER_RETURN_DELAY_TIME     = [  9, 1]
DXL_REGISTER_OPERATING_MODE        = [ 11, 1]
DXL_REGISTER_HOMING_OFFSET         = [ 20, 4]
DXL_REGISTER_TEMPERATURE_LIMIT     = [ 31, 1]
DXL_REGISTER_MAX_VOLTAGE_LIMIT     = [ 32, 2]
DXL_REGISTER_MIN_VOLTAGE_LIMIT     = [ 34, 2]
DXL_REGISTER_PWM_LIMIT             = [ 36, 2]
DXL_REGISTER_CURRENT_LIMIT         = [ 38, 2]
DXL_REGISTER_VELOCITY_LIMIT        = [ 44, 4]
DXL_REGISTER_MAX_POSITION_LIMIT    = [ 48, 4]
DXL_REGISTER_MIN_POSITION_LIMIT    = [ 52, 4]
DXL_REGISTER_TORQUE_ENABLE         = [ 64, 1]
DXL_REGISTER_HARDWARE_ERROR_STATUS = [ 70, 1]
DXL_REGISTER_VELOCITY_I_GAIN       = [ 76, 2]
DXL_REGISTER_VELOCITY_P_GAIN       = [ 78, 2]
DXL_REGISTER_POSITION_D_GAIN       = [ 80, 2]
DXL_REGISTER_POSITION_I_GAIN       = [ 82, 2]
DXL_REGISTER_POSITION_P_GAIN       = [ 84, 2]
DXL_REGISTER_GOAL_PWM              = [100, 2]
DXL_REGISTER_GOAL_CURRENT          = [102, 2]
DXL_REGISTER_GOAL_VELOCITY         = [104, 4]
DXL_REGISTER_GOAL_POSITION         = [116, 4]
DXL_REGISTER_PRESENT_PWM           = [124, 2]
DXL_REGISTER_PRESENT_CURRENT       = [126, 2]
DXL_REGISTER_PRESENT_VELOCITY      = [128, 4]
DXL_REGISTER_PRESENT_POSITION      = [132, 4]
DXL_REGISTER_PRESENT_INPUT_VOLTAGE = [144, 2]
DXL_REGISTER_PRESENT_TEMPERATURE   = [146, 1]
DXL_REGISTER_INDIRECT_ADDRESS      = [168, 2]
DXL_REGISTER_INDIRECT_DATA         = [208, 1]

# ------------------------------
# DXL PROPERTY
# ------------------------------
DXL_ID                = 0
DXL_POSITION_LIMIT    = 1
DXL_CURRENT_LIMIT     = 2
DXL_TEMPERATURE_LIMIT = 3
DXL_POSITION_PID      = 4
DXL_RETURN_DELAY_TIME = 5

DXL_POSITION_UNIT = 0.00153398078  # radian/pulse
DXL_VELOCITY_UNIT = 0.02398082392  # radian/s/pulse
DXL_CURRENT_UNIT  = 0.001          # A/mA
DXL_TIME_UNIT     = 0.000002       # s/us

DXL_INDEX_MCP_PITCH_R  = 1
DXL_INDEX_PIP_PITCH_R  = 2
DXL_MIDDLE_MCP_PITCH_R = 3
DXL_MIDDLE_PIP_PITCH_R = 4
DXL_THUMB_MCP_PITCH_R  = 5
DXL_THUMB_PIP_PITCH_R  = 6
DXL_PALM_AXIAL_R       = 7

DXL_INDEX_MCP_PITCH_L  = 8
DXL_INDEX_PIP_PITCH_L  = 9
DXL_MIDDLE_MCP_PITCH_L = 10
DXL_MIDDLE_PIP_PITCH_L = 11
DXL_THUMB_MCP_PITCH_L  = 12
DXL_THUMB_PIP_PITCH_L  = 13
DXL_PALM_AXIAL_L       = 14

# ------------------------------
# DXL ID
# ------------------------------
HAND_R_DXL_ID_LIST = [DXL_INDEX_MCP_PITCH_R, DXL_INDEX_PIP_PITCH_R, DXL_MIDDLE_MCP_PITCH_R, DXL_MIDDLE_PIP_PITCH_R, DXL_THUMB_MCP_PITCH_R, DXL_THUMB_PIP_PITCH_R, DXL_PALM_AXIAL_R]
HAND_L_DXL_ID_LIST = [DXL_INDEX_MCP_PITCH_L, DXL_INDEX_PIP_PITCH_L, DXL_MIDDLE_MCP_PITCH_L, DXL_MIDDLE_PIP_PITCH_L, DXL_THUMB_MCP_PITCH_L, DXL_THUMB_PIP_PITCH_L, DXL_PALM_AXIAL_L]

HAND_DXL_ID_LIST = HAND_R_DXL_ID_LIST + HAND_L_DXL_ID_LIST

ROBOT_DXL_ID_LIST = HAND_DXL_ID_LIST

for dxl in ROBOT_DXL_ID_LIST:
    DXL[DXL_ID][dxl] = dxl

# ------------------------------
# DXL RETURN DELAY TIME (0 ~ 0.000508s)
# ------------------------------
DXL[DXL_RETURN_DELAY_TIME][DXL_INDEX_MCP_PITCH_R]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_INDEX_PIP_PITCH_R]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_MIDDLE_MCP_PITCH_R] = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_MIDDLE_PIP_PITCH_R] = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_THUMB_MCP_PITCH_R]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_THUMB_PIP_PITCH_R]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_PALM_AXIAL_R]       = 0

DXL[DXL_RETURN_DELAY_TIME][DXL_INDEX_MCP_PITCH_L]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_INDEX_PIP_PITCH_L]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_MIDDLE_MCP_PITCH_L] = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_MIDDLE_PIP_PITCH_L] = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_THUMB_MCP_PITCH_L]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_THUMB_PIP_PITCH_L]  = 0
DXL[DXL_RETURN_DELAY_TIME][DXL_PALM_AXIAL_L]       = 0

for dxl in ROBOT_DXL_ID_LIST:
    DXL[DXL_RETURN_DELAY_TIME][dxl] = int(DXL[DXL_RETURN_DELAY_TIME][dxl] / DXL_TIME_UNIT)

# ------------------------------
# DXL POSITION LIMIT
# ------------------------------
DXL[DXL_POSITION_LIMIT][DXL_INDEX_MCP_PITCH_R]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_INDEX_PIP_PITCH_R]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_MIDDLE_MCP_PITCH_R] = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_MIDDLE_PIP_PITCH_R] = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_THUMB_MCP_PITCH_R]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_THUMB_PIP_PITCH_R]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_PALM_AXIAL_R]       = [0, 4095]

DXL[DXL_POSITION_LIMIT][DXL_INDEX_MCP_PITCH_L]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_INDEX_PIP_PITCH_L]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_MIDDLE_MCP_PITCH_L] = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_MIDDLE_PIP_PITCH_L] = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_THUMB_MCP_PITCH_L]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_THUMB_PIP_PITCH_L]  = [0, 4095]
DXL[DXL_POSITION_LIMIT][DXL_PALM_AXIAL_L]       = [0, 4095]

# for dxl in ROBOT_DXL_ID_LIST:
#     DXL[DXL_POSITION_LIMIT][dxl][0] = int(DXL[DXL_POSITION_LIMIT][dxl][0] / DXL_POSITION_UNIT)
#     DXL[DXL_POSITION_LIMIT][dxl][1] = int(DXL[DXL_POSITION_LIMIT][dxl][1] / DXL_POSITION_UNIT)

# ------------------------------
# DXL CURRENT LIMIT (0 ~ 1.75A)
# ------------------------------
DXL[DXL_CURRENT_LIMIT][DXL_INDEX_MCP_PITCH_R]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_INDEX_PIP_PITCH_R]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_MIDDLE_MCP_PITCH_R] = 1
DXL[DXL_CURRENT_LIMIT][DXL_MIDDLE_PIP_PITCH_R] = 1
DXL[DXL_CURRENT_LIMIT][DXL_THUMB_MCP_PITCH_R]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_THUMB_PIP_PITCH_R]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_PALM_AXIAL_R]       = 1

DXL[DXL_CURRENT_LIMIT][DXL_INDEX_MCP_PITCH_L]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_INDEX_PIP_PITCH_L]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_MIDDLE_MCP_PITCH_L] = 1
DXL[DXL_CURRENT_LIMIT][DXL_MIDDLE_PIP_PITCH_L] = 1
DXL[DXL_CURRENT_LIMIT][DXL_THUMB_MCP_PITCH_L]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_THUMB_PIP_PITCH_L]  = 1
DXL[DXL_CURRENT_LIMIT][DXL_PALM_AXIAL_L]       = 1

for dxl in ROBOT_DXL_ID_LIST:
    DXL[DXL_CURRENT_LIMIT][dxl] = int(DXL[DXL_CURRENT_LIMIT][dxl] / DXL_CURRENT_UNIT)

# ------------------------------
# DXL TEMPERATURE LIMIT (0 ~ 100°C)
# ------------------------------
DXL[DXL_TEMPERATURE_LIMIT][DXL_INDEX_MCP_PITCH_R]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_INDEX_PIP_PITCH_R]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_MIDDLE_MCP_PITCH_R] = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_MIDDLE_PIP_PITCH_R] = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_THUMB_MCP_PITCH_R]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_THUMB_PIP_PITCH_R]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_PALM_AXIAL_R]       = 80

DXL[DXL_TEMPERATURE_LIMIT][DXL_INDEX_MCP_PITCH_L]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_INDEX_PIP_PITCH_L]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_MIDDLE_MCP_PITCH_L] = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_MIDDLE_PIP_PITCH_L] = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_THUMB_MCP_PITCH_L]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_THUMB_PIP_PITCH_L]  = 80
DXL[DXL_TEMPERATURE_LIMIT][DXL_PALM_AXIAL_L]       = 80

# ------------------------------
# DXL POSITION PID GAINS (0 ~ 16383)
# ------------------------------
DXL[DXL_POSITION_PID][DXL_INDEX_MCP_PITCH_R]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_INDEX_PIP_PITCH_R]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_MIDDLE_MCP_PITCH_R] = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_MIDDLE_PIP_PITCH_R] = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_THUMB_MCP_PITCH_R]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_THUMB_PIP_PITCH_R]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_PALM_AXIAL_R]       = [2000, 0, 0]

DXL[DXL_POSITION_PID][DXL_INDEX_MCP_PITCH_L]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_INDEX_PIP_PITCH_L]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_MIDDLE_MCP_PITCH_L] = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_MIDDLE_PIP_PITCH_L] = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_THUMB_MCP_PITCH_L]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_THUMB_PIP_PITCH_L]  = [2000, 0, 0]
DXL[DXL_POSITION_PID][DXL_PALM_AXIAL_L]       = [2000, 0, 0]